.TH AFDKO 1 "JUL 2020" Linux "User Manuals"
.SH NAME
afdko \- wrapper for afdko utilities
.SH SYNOPSIS
.br
.B afdko
[utility] [params]
.SH DESCRIPTION
.B afdko
calls the utilities from AFDKO (Adobe Font Development Kit for OpenType).
.PP
To see available utilities in afdko, run
.B afdko
without command.
.SH AUTHOR
This
.B afdko
wrapper is created by Yao Wei <mwei@debian.org>.
.br
The binaries this wrapper calls are created by Adobe System Incorporated.
